@echo off
REM ===================================================================
REM   DEPLOY_STRIPE_LINKS.bat   (2026-05-13)
REM   Ships the live Stripe Payment Link URLs into:
REM     - audit-quiz.html (quiz-result tier mapping)
REM     - thank-you.html  (post-booking continue-now mapping)
REM
REM   Generated by stripe_setup_v2_paymentlinks.py:
REM     AI_SPECIALIST  https://buy.stripe.com/28E14p3xb5TG9Nw8JodQQ0b
REM     AI_TEAM        https://buy.stripe.com/28E28taZD1Dqe3MbVAdQQ0c
REM     AI_DEPARTMENT  https://buy.stripe.com/aFaeVf9Vzdm84tc8JodQQ0d
REM
REM   Pattern matches DEPLOY_V5_FIX.bat — clears stale .git locks then
REM   targeted-stages just the two modified files.
REM ===================================================================

cd /d "%~dp0"
echo.
echo [stripe-links] Working in: %CD%
echo.

REM 1. Clear stale git locks (OneDrive sync sometimes leaves these)
if exist ".git\index.lock"   del /f /q ".git\index.lock"
if exist ".git\HEAD.lock"    del /f /q ".git\HEAD.lock"
if exist ".git\config.lock"  del /f /q ".git\config.lock"

REM 2. Reset index without disturbing the working tree
git reset HEAD >NUL 2>&1

REM 3. Stage only the two intentional files
git add audit-quiz.html
git add thank-you.html

REM 4. Show what's staged so the operator can sanity-check before push
echo.
echo [stripe-links] Staged for commit:
git diff --cached --stat
echo.

REM 5. Commit
git commit -m "stripe: wire live Payment Link URLs into audit-quiz + thank-you" -m "Replaces buy.stripe.com/placeholder-ai-{specialist,team,department} in audit-quiz.html and thank-you.html with the real Payment Links generated 2026-05-13 by scripts/stripe_setup_v2_paymentlinks.py. Quiz tier mapping (Specialist/Team/Department) and the post-booking 'continue now' CTA both now route to live Stripe checkout. Webhook endpoint we_1TWcy9 -> https://webhook.efficio.tech/stripe/webhook is registered with the 5 onboarding events; signing secret written to .env. Idempotent: re-running the helper is a no-op."

REM 6. Push
git push origin main

echo.
echo [stripe-links] Done. Pages live in 30-90s.
echo.
echo Verify:
echo   curl -s https://efficio.tech/audit-quiz ^| findstr "28E14p3xb5TG"
echo   curl -s https://efficio.tech/thank-you   ^| findstr "28E14p3xb5TG"
echo.
pause
